import requests

HOST = "https://release-gs.qa-playground.com/api/v1"

response = requests.get(
    url=f"{HOST}/users",
    headers={"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IldGZlRBQ0hzYUhvQ3VML1MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL215a290cWJvY2t6dnphY2NjdWJ6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJmNjIxNGFmYS1lNTIwLTQzODMtYjUxZi1iODY3N2I3NGRjOTciLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzI2OTAwMTU5LCJpYXQiOjE3MjYzMDAxNTksImVtYWlsIjoiaG9sYmluYWliYUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiaG9sYmluYWliYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZ1bGxfbmFtZSI6IkFpYmVrIiwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiJmNjIxNGFmYS1lNTIwLTQzODMtYjUxZi1iODY3N2I3NGRjOTcifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJlbWFpbC9zaWdudXAiLCJ0aW1lc3RhbXAiOjE3MjYzMDAxNTl9XSwic2Vzc2lvbl9pZCI6ImIxMTczMzdlLTZkNDctNDc4ZS05MjJjLWEwYWI1NzczMDIyNSIsImlzX2Fub255bW91cyI6ZmFsc2V9.4Tp9iGj-DicjJ-EpQHVYEhraWazrT18xD0eAIUW18HM",
             "X-Task-Id": "API-1"
             },
)

print(response.json())